[package]
name = "keep_screen_on_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"

[target.x86_64-unknown-linux-gnu.dependencies]
dbus = "0.9.10"
lazy_static = "1.5.0"

[target.x86_64-pc-windows-msvc.dependencies]
windows = "0.62.2"
