[package]
name = "keep_screen_on_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"

[target.x86_64-unknown-linux-gnu.dependencies]
dbus = "0.9.10"

[target.x86_64-pc-windows-msvc.dependencies]
windows = "0.62.2"
